export const category = [
    'TOUTES CATEGORIES',
    'ANIMAUX',
    'ART & PHOTO',
    'ARTISANAT & CUISINE',
    'AUTOMOBILE',
    'BD',
    'EDITION & JOURNAL.',
    'ENFANCE & EDUC.',
    'ENVIRONNEMENT',
    'FILM & VIDÉO',
    'JEUX',
    'MODE & DESIGN',
    'MUSIQUE',
    'SANTÉ & BIEN-ÊTRE',
    'SOLIDAIRE & CITOYEN',
    'SPECTACLE VIVANT',
    'SPORTS',
    'TECHNOLOGIE',
    'AUTRES PROJETS',
  ];